import React from 'react';
import { X } from 'lucide-react';

interface LegalModalProps {
  isOpen: boolean;
  onClose: () => void;
  type: 'privacy' | 'terms' | 'status' | null;
}

const LegalModal: React.FC<LegalModalProps> = ({ isOpen, onClose, type }) => {
  if (!isOpen || !type) return null;

  const content = {
    privacy: {
      title: "Privacy Policy",
      body: (
        <>
          <p>At Pathforge, we take your privacy seriously. This policy outlines how we collect, use, and protect your data.</p>
          <h3>1. Information Collection</h3>
          <p>We collect basic profile information (name, email) and your quiz responses to generate accurate career roadmaps.</p>
          <h3>2. Data Security</h3>
          <p>All data is encrypted in transit and at rest using industry-standard SSL and database security protocols (powered by Supabase).</p>
          <h3>3. Third-Party Sharing</h3>
          <p>We do not sell your personal data. We may share anonymized prompts with AI providers to generate your roadmaps, but your personal identity is never included.</p>
        </>
      )
    },
    terms: {
      title: "Terms of Service",
      body: (
        <>
          <p>By using Pathforge, you agree to these terms.</p>
          <h3>1. Acceptance of Terms</h3>
          <p>By creating an account, you agree to use the service responsibly and not for any malicious purposes.</p>
          <h3>2. AI-Generated Content</h3>
          <p>The career roadmaps generated by our AI are for informational purposes only. We do not guarantee employment or specific career outcomes.</p>
          <h3>3. Account Termination</h3>
          <p>We reserve the right to suspend or terminate accounts that violate our terms of service or attempt to abuse the platform.</p>
        </>
      )
    },
    status: {
      title: "System Status",
      body: (
        <div style={{ textAlign: 'center', padding: '2rem 0' }}>
          <div style={{ display: 'inline-flex', alignItems: 'center', gap: '0.5rem', background: 'rgba(34, 197, 94, 0.1)', color: '#22c55e', padding: '0.5rem 1rem', borderRadius: '4px', border: '1px solid rgba(34, 197, 94, 0.2)' }}>
            <span style={{ width: 8, height: 8, borderRadius: '50%', background: '#22c55e', display: 'inline-block', boxShadow: '0 0 8px #22c55e' }}></span>
            <strong style={{ fontFamily: 'var(--font-label)', letterSpacing: '0.1em' }}>ALL SYSTEMS OPERATIONAL</strong>
          </div>
          
          <ul style={{ listStyle: 'none', padding: 0, marginTop: '2rem', textAlign: 'left' }}>
            <li style={{ display: 'flex', justifyContent: 'space-between', padding: '0.75rem 0', borderBottom: '1px solid var(--color-rule)' }}>
              <span>Authentication (Supabase)</span>
              <span style={{ color: '#22c55e' }}>Operational</span>
            </li>
            <li style={{ display: 'flex', justifyContent: 'space-between', padding: '0.75rem 0', borderBottom: '1px solid var(--color-rule)' }}>
              <span>Database Cluster</span>
              <span style={{ color: '#22c55e' }}>Operational</span>
            </li>
            <li style={{ display: 'flex', justifyContent: 'space-between', padding: '0.75rem 0', borderBottom: '1px solid var(--color-rule)' }}>
              <span>AI Inference Engine</span>
              <span style={{ color: '#22c55e' }}>Operational</span>
            </li>
            <li style={{ display: 'flex', justifyContent: 'space-between', padding: '0.75rem 0', borderBottom: '1px solid var(--color-rule)' }}>
              <span>Frontend CDN</span>
              <span style={{ color: '#22c55e' }}>Operational</span>
            </li>
          </ul>
        </div>
      )
    }
  };

  const { title, body } = content[type];

  return (
    <div className="mobile-backdrop" style={{ display: 'flex', alignItems: 'center', justifyContent: 'center' }}>
      <div className="lumen-document" style={{ width: '100%', maxWidth: '600px', maxHeight: '80vh', overflowY: 'auto', position: 'relative', margin: '1rem', background: 'var(--color-paper-2)' }}>
        <button 
          onClick={onClose}
          style={{ position: 'absolute', right: '1rem', top: '1rem', background: 'transparent', border: 'none', color: 'var(--color-ink-2)', cursor: 'pointer' }}
          aria-label="Close"
        >
          <X size={20} />
        </button>
        
        <h2 style={{ marginTop: 0, fontFamily: 'var(--font-serif)', fontSize: '2rem', borderBottom: '1px solid var(--color-rule)', paddingBottom: '1rem', marginBottom: '1.5rem' }}>
          {title}
        </h2>
        
        <div style={{ lineHeight: 1.6 }}>
          {body}
        </div>
        
        <div style={{ marginTop: '2rem', textAlign: 'right' }}>
          <button className="btn btn--outline" onClick={onClose}>close</button>
        </div>
      </div>
    </div>
  );
};

export default LegalModal;
